const express = require("express");
const { requireApiKey } = require("../middleware/auth");
const { PROVIDERS, getPricing, getModelTier } = require("../config/pricing");
const { createPurchaseOrder, submitPaymentSlip, logAuditEvent, getProfileByApiKey, updateProfile, verifyPassword, getUser, getOfferStatus, claimOffer, getModelTokenBalances } = require("../utils/db");
const QRCode = require("qrcode");
const generatePromptPayPayload = require("promptpay-qr");
const multer = require("multer");
const router = express.Router();
const MARKUP = 2;
const USD_TO_THB = Number(process.env.USD_TO_THB || 36.5);
const slipUpload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 8 * 1024 * 1024 }, fileFilter: (req,file,cb) => cb(null, file.mimetype.startsWith("image/")) });
const tierFor = getModelTier;
router.get("/profile", requireApiKey, async (req,res,next) => { try { const user=await getProfileByApiKey(req.apiKey); const modelTokens=await getModelTokenBalances(req.apiKey); res.json({ name:req.keyRecord.name, username:user?.username, email:user?.email || null, tier:req.keyRecord.tier, tokenBalance:req.keyRecord.tokenBalance, tokenPlanLimit:req.keyRecord.tokenPlanLimit, modelTokens, purchasedModels:req.keyRecord.purchasedModels, markupPercent:100, plans:{ plus:{priceThb:299,chatPerMonth:100}, max:{priceThb:499,chatPerMonth:400} } }); } catch(e){next(e)} });
router.get("/offer/gpt5", requireApiKey, async (req,res,next) => { try { const claim=await getOfferStatus(req.apiKey,"gpt5-100k"); res.json({ eligible:["free","plus"].includes(req.keyRecord.tier), claim, model:"openai/gpt-5.6-terra", tokens:100000 }); } catch(e){next(e)} });
router.post("/offer/gpt5", requireApiKey, async (req,res,next) => { try { const { decision, termsAccepted, privacyAccepted }=req.body||{}; if(!["accepted","declined"].includes(decision))return res.status(400).json({error:"invalid offer decision"}); if(decision==="accepted" && (!termsAccepted || !privacyAccepted))return res.status(400).json({error:"ต้องยอมรับ TOS และ Privacy ก่อนรับ offer"}); if(!["free","plus"].includes(req.keyRecord.tier))return res.status(403).json({error:"offer นี้สำหรับ Free และ Plus tier"}); const result=await claimOffer(req.apiKey,"gpt5-100k",decision,Boolean(termsAccepted),Boolean(privacyAccepted)); res.json(result); } catch(e){next(e)} });
router.patch("/profile", requireApiKey, async (req,res,next) => { try { const { email, currentPassword, newPassword, newPasswordConfirm }=req.body||{}; const user=await getProfileByApiKey(req.apiKey); if(!user)return res.status(404).json({error:"ไม่พบ profile"}); if(email!==undefined && (typeof email!=="string" || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim())))return res.status(400).json({error:"กรุณาใส่ email ที่ถูกต้อง"}); if(newPassword && newPassword.length<8)return res.status(400).json({error:"password ใหม่ต้องยาวอย่างน้อย 8 ตัวอักษร"}); if(newPassword!==newPasswordConfirm)return res.status(400).json({error:"รหัสผ่านใหม่สองช่องไม่ตรงกัน"}); const storedUser=await getUser(user.username); if(newPassword && !verifyPassword(currentPassword||"", storedUser.salt, storedUser.password_hash))return res.status(403).json({error:"รหัสผ่านปัจจุบันไม่ถูกต้อง"}); const updated=await updateProfile(req.apiKey,{email:email===undefined?undefined:email.trim().toLowerCase(),password:newPassword}); res.json({profile:updated}); } catch(e){ if(e.code==='23505') return res.status(409).json({error:"email นี้ถูกใช้แล้ว"}); next(e); } });
router.get("/catalog", requireApiKey, (req,res) => res.json({ markupPercent:20, providers: Object.fromEntries(Object.entries(PROVIDERS).map(([p,c]) => [p,{label:c.label,models:Object.entries(c.models).map(([id,m])=>({id,label:m.label,input:m.input,output:m.output,tier:tierFor(p,id)}))}])) }));
router.post("/checkout", requireApiKey, async (req,res,next) => { try {
  const { provider, model, inputTokens=0, outputTokens=0, tier } = req.body || {};
  const p = provider && model ? getPricing(provider,model) : null;
  const input = Math.max(0, Math.floor(Number(inputTokens)||0)), output = Math.max(0, Math.floor(Number(outputTokens)||0));
  const amount = p ? ((input/1e6)*p.input + (output/1e6)*p.output)*MARKUP : 0;
  const amountThb = tier === "plus" ? 299 : tier === "max" ? 499 : Math.round(amount * USD_TO_THB * 100) / 100;
  if (!p && !amountThb) return res.status(400).json({ error: "เลือก Plus หรือ Max เท่านั้น" });
  if (p && p.input === 0 && p.output === 0) return res.status(400).json({ error: "model ฟรีไม่รองรับการเติม token" });
  if (amountThb > 0 && !process.env.PROMPTPAY_ID) return res.status(503).json({ error: "ยังไม่ได้ตั้งค่า PromptPay สำหรับรับชำระ" });
  if (p && input + output < 1000) return res.status(400).json({error:"ซื้อขั้นต่ำ 1,000 token"});
  if (p && tier) return res.status(400).json({error:"เลือก plan หรือ topup token อย่างใดอย่างหนึ่ง"});
  const order = await createPurchaseOrder({apiKey:req.apiKey,kind:p?"token":"tier",tier:tier || (p && tierFor(provider,model)),provider,model,inputTokens:input,outputTokens:output,amountUsd:amount,amountThb});
  await logAuditEvent({eventType:"checkout_created",username:req.keyRecord.name,ipAddress:req.ip,method:req.method,path:req.path,statusCode:201,metadata:{orderId:order.id,kind:order.kind,amountUsd:Number(order.amount_usd)}});
  const qrText = amountThb ? generatePromptPayPayload(String(process.env.PROMPTPAY_ID).replace(/\D/g, ""), { amount: amountThb }) : `DUMMY-PAYMENT:${order.id}`;
  const qrDataUrl = await QRCode.toDataURL(qrText, { width: 260, margin: 2 });
  res.status(201).json({orderId:order.id,status:"pending",amountThb,amountUsd:Number(order.amount_usd),tokens:input+output,model,qrText,qrDataUrl,expiresAt:order.expires_at,notice: amountThb ? "สแกนและชำระตามยอด จากนั้นอัปโหลดสลิปเพื่อรอ Admin อนุมัติ" : "QR นี้เป็นตัวอย่าง ยังไม่มีการตัดเงินหรือเติมเครดิต"});
} catch(e){next(e)} });
router.post("/orders/:id/slip", requireApiKey, slipUpload.single("slip"), async (req,res,next) => { try { if (!req.file) return res.status(400).json({error:"กรุณาแนบรูปสลิป"}); const order=await submitPaymentSlip(req.params.id,req.apiKey,req.file); if(!order)return res.status(404).json({error:"ไม่พบ order หรือส่งสลิปไปแล้ว"}); await logAuditEvent({eventType:"payment_slip_submitted",username:req.keyRecord.name,ipAddress:req.ip,method:req.method,path:req.path,statusCode:201,metadata:{orderId:req.params.id}}); res.status(201).json({order}); } catch(e){next(e)} });
module.exports = router;
